var products = [
	{
		'image': '//1452453094.rsc.cdn77.org/r-0000000/public/products/csshat2_Dre9qUh.png',
		'download_links': {
			'exe': '/download/csshat2/exe/',
			'zip': '/download/csshat2/zip/',
			'dmg': '/download/csshat2/dmg/'
		},
		'licensed': 'True',
		'visible': 'True',
		'video': '//1452453094.rsc.cdn77.org/r-0000000/public/products/videos/csshat2.mp4',
		'id': 53,
		'current_version': 20101,
		'targets': 'dmg,exe,zip',
		'last_update_date_formated': 'Feb 12, 2016',
		'author': 'Source',
		'support': 'Photoshop CC2014, CC2015',
		'license_required': 'True',
		'platform': 'Photoshop',
		'buy_url': '/payment/csshat2/',
		'internal_name': 'csshat2',
		'os_free': 'False',
		'badge': '30% Off',
		'order_priority': 1,
		'author_url': 'https://madebysource.com/',
		'description': 'Photoshop plugin which instantly turns layer to code. This new update comes with syntax highlighting, custom code template, middlewares, live preview and more.',
		'price': '34.99',
		'old_price': '49.99',
		'old_price_split': ['49', '99'],
		'price_split': ['34', '99'],
		'badge_color': '#56A1F6',
		'key_features': ['Select any Photoshop Layer and get CSS instantly.', 'Colors, gradients, sizes, borders', 'Font styles and paragraph styles', 'Simple to use and easy to read'],
		'name': 'CSS Hat 2',
		'url': 'https://csshat.com/',
		'short_description': 'Photoshop plugin which instantly turns layer to code. ',
		'download_count': 15001,
		'current_version_formatted': '2.1.1',
		'popular': 'True',
		'bf_line': 'Turns layer to code with live preview!'
	},
	{
		'image': '//1452453094.rsc.cdn77.org/r-0000000/public/products/svglayers.png',
		'download_links': {
			'zip': '/download/svglayers/zip/'
		},
		'licensed': 'True',
		'visible': 'True',
		'video': '//1452453094.rsc.cdn77.org/r-0000000/public/products/videos/svglayers_jeh4qIA.mp4',
		'id': 80,
		'current_version': 10000,
		'targets': 'zip',
		'last_update_date_formated': 'Oct 18, 2016',
		'author': 'Rune Lund-Hermansen',
		'support': 'Photoshop CS5+',
		'license_required': 'True',
		'platform': 'Photoshop',
		'buy_url': '/payment/svglayers/',
		'internal_name': 'svglayers',
		'os_free': 'False',
		'badge': '30% Off',
		'order_priority': 2,
		'author_url': 'http://svglayers.com/',
		'description': 'Need proper SVG support in Photoshop? SVG Layers lets you import SVG files as editable vector layers and export clean SVGs directly from Photoshop. Using SVGs becomes much easier when you don’t have to leave Photoshop to change a color or adjust a few shapes. Instead, edit the SVG directly in the context of your design and when you’re done editing you can export back to SVG as proper scalable vectors.',
		'price': '6.99',
		'old_price': '9.99',
		'old_price_split': ['9', '99'],
		'price_split': ['6', '99'],
		'badge_color': '#56A1F6',
		'key_features': ['Import SVG files as editable vector layers', 'Edit SVGs directly in Photoshop', 'Export clean and scalable SVG files'],
		'name': 'SVG Layers',
		'url': 'http://svglayers.com/',
		'short_description': 'SVG Layers lets you import SVG files as editable vector layers and export clean SVGs directly from Photoshop',
		'download_count': 239,
		'current_version_formatted': '1.0.0',
		'popular': 'True',
		'bf_line': 'Import SVGs, customize as shapes and export as to SVG'
	},
	 {
		'image': '//1452453094.rsc.cdn77.org/r-0000000/public/products/pngexpress.png',
		'download_links': {
			'zip': '/download/pngexpress/zip/'
		},
		'licensed': 'True',
		'visible': 'True',
		'video': '//1452453094.rsc.cdn77.org/r-0000000/public/products/videos/pngexpress.mp4',
		'id': 79,
		'current_version': 10000,
		'targets': 'zip',
		'last_update_date_formated': 'Oct 18, 2016',
		'author': 'Rune Lund-Hermansen',
		'support': 'Photoshop CS5+',
		'license_required': 'True',
		'platform': 'Photoshop',
		'buy_url': '/payment/pngexpress/',
		'internal_name': 'pngexpress',
		'os_free': 'False',
		'badge': '',
		'order_priority': 3,
		'author_url': 'http://pngexpress.com/',
		'description': 'Need a better way to export assets & specs from Photoshop? PNG Express makes it incredibly easy to export assets for all iOS, Android, and web densities in one go from any source resolution. It supports multiple asset states, PNG optimisation, Android 9-patches, XML/JSON/HTML output, Xcode Asset Catalog integration and more. Most importantly, PNG Express gets out of your way while you design and gives you full control and repeatability of exports. This makes it an ideal tool for iterative workflows and team work. It also generates matching design specifications with concise information on sizes, distances, font features and more. PNG Express is being trusted daily for demanding work by amazing designers and teams around the world. Get on board!',
		'price': '29.99',
		'old_price': 'None',
		'old_price_split': ['None'],
		'price_split': ['29', '99'],
		'badge_color': '',
		'key_features': ['Easy export to all iOS, Android and Web densities', 'Unrivalled flexibility and scaling accuracy', 'Export to PNG, JPG, and SVG', 'Supports optimised PNGs and Android 9-patches', 'Create concise design specs in a snap', 'Spec position, size, distance, shape, font and FXs'],
		'name': 'PNG Express',
		'url': 'http://pngexpress.com/',
		'short_description': 'A better way to export assets & specs from Photoshop',
		'download_count': 103,
		'current_version_formatted': '1.0.0',
		'popular': 'True',
		'bf_line': 'Export assets & specs from Photoshop for all devices'
	}, 
	{
		'image': '//1452453094.rsc.cdn77.org/r-0000000/public/products/sketch-runner.png',
		'download_links': {
			'zip': '/download/sketch-runner/zip/'
		},
		'licensed': 'True',
		'visible': 'True',
		'video': '//1452453094.rsc.cdn77.org/r-0000000/public/products/videos/sketch-runner.mp4',
		'id': 78,
		'current_version': 702,
		'targets': 'zip',
		'last_update_date_formated': 'Oct 11, 2016',
		'author': 'Sketch Runner',
		'support': 'Sketch 37+',
		'license_required': 'False',
		'platform': 'Sketch',
		'buy_url': '/signup/sketch-runner/',
		'internal_name': 'sketch-runner',
		'os_free': 'False',
		'badge': '',
		'order_priority': 67,
		'author_url': 'http://sketchrunner.com/',
		'description': 'Runner helps you to get around Sketch quicker by giving you an intuitive interface to supercharge your daily workflow. Stop searching through your menu & start running commands directly from your keyboard.',
		'price': 'None',
		'old_price': 'None',
		'old_price_split': ['None'],
		'price_split': ['None'],
		'badge_color': '',
		'key_features': ['Run Sketch menu items and third party plugin actions', 'Jump anywhere in your document', 'Search and insert or replace symbols', 'Create symbols or styles on the fly', 'Apply styles to one or multiple layers'],
		'name': 'Sketch Runner',
		'url': 'http://sketchrunner.com/',
		'short_description': 'Runner helps you to get around Sketch quicker by giving you an intuitive interface to supercharge your daily workflow. Stop searching through your menu & start running commands directly from your keyboard.',
		'download_count': 733,
		'current_version_formatted': '0.7.2',
		'popular': 'True',
		'bf_line': 'Spotlight in Sketch, run plugins, create objects...'
	}, 
	{
		'image': '//1452453094.rsc.cdn77.org/r-0000000/public/products/guide-guide.png',
		'download_links': {
			'exe': '/download/guideguide/exe/',
			'zip': '/download/guideguide/zip/',
			'dmg': '/download/guideguide/dmg/'
		},
		'licensed': 'True',
		'visible': 'True',
		'video': '//1452453094.rsc.cdn77.org/r-0000000/public/products/videos/guide-guide.mp4',
		'id': 68,
		'current_version': 40501,
		'targets': 'dmg,exe,zip',
		'last_update_date_formated': 'Sep 16, 2016',
		'author': 'Cameron McEfee',
		'support': 'Photoshop CC+',
		'license_required': 'True',
		'platform': 'Photoshop',
		'buy_url': '/payment/guide-guide/',
		'internal_name': 'guideguide',
		'os_free': 'False',
		'badge': '',
		'order_priority': 68,
		'author_url': 'http://guideguide.me/',
		'description':  "  Whether you need to create responsive grids, measure columns with margins, or just find the middle of things, GuideGuide has tools that will make your life easier.  Every feature works with your document, artboards, layers, and even your selection, so that you can add, remove, and duplicate exactly the guides you want.  You can also take advantage of it's handy abilities to add guides at the top, left, bottom, right, and midpoints of your document, artboards, or selected layers. You can even duplicate guides between artboards and documents.  GuideGuide has been around since 2010, has created millions of guides, and is Photoshop's most installed third-party extension.  Follow GuideGuide on Twitter for occasional announcements about new releases: https://twitter.com/guideguide",
		'price': '9.99',
		'old_price': 'None',
		'old_price_split': ['None'],
		'price_split': ['9', '99'],
		'badge_color': '',
		'key_features': ['Easily create custom grids', 'Quickly add and remove guides', 'Works based on document, artboard, or selection', 'Create complex layouts with grid notation', 'Save and share frequently used grids', 'Duplicate guides between artboards'],
		'name': 'Guide Guide',
		'url': 'http://guideguide.me/',
		'short_description': 'The grids and guides extension for Photoshop',
		'download_count': 608,
		'current_version_formatted': '4.5.1',
		'popular': 'True',
		'bf_line': 'Layout guides management made awesome'
	}, 
	{
		'image': '//1452453094.rsc.cdn77.org/r-0000000/public/products/perspective-mockups.png',
		'download_links': {
			'exe': '/download/perspective-mockups/exe/',
			'zip': '/download/perspective-mockups/zip/',
			'dmg': '/download/perspective-mockups/dmg/'
		},
		'licensed': 'True',
		'visible': 'True',
		'video': '//1452453094.rsc.cdn77.org/r-0000000/public/products/videos/perspective-mockups.mp4',
		'id': 77,
		'current_version': 10000,
		'targets': 'dmg,exe,zip',
		'last_update_date_formated': 'Sep 13, 2016',
		'author': 'Perspective Mockups',
		'support': 'Photoshop CC 2015.5. only',
		'license_required': 'True',
		'platform': 'Photoshop',
		'buy_url': '/payment/perspective-mockups/',
		'internal_name': 'perspective-mockups',
		'os_free': 'False',
		'badge': 'Trending',
		'order_priority': 69,
		'author_url': 'http://perspectivemockups.com/',
		'description':  "Photoshop Plugin to transform your work into a unique perspective. All Perspective Mockups Photoshop actions are fully customizable and editable. We don't flatten any layers so you have the ability to fully customize each action and presentation to your needs and designs.",
		'price': '19.99',
		'old_price': 'None',
		'old_price_split': ['None'],
		'price_split': ['19', '99'],
		'badge_color': '#56A1F6',
		'key_features': ['Give your project a perspective', 'Showcase it in different situations', 'Select ideal mockup for you or edit it to fit your needs', ''],
		'name': 'Perspective Mockups',
		'url': 'http://perspectivemockups.com/',
		'short_description': 'Photoshop Plugin to transform your work into a unique perspective. ',
		'download_count': 18242,
		'current_version_formatted': '1.0.0',
		'popular': 'True',
		'bf_line': 'Turns your design in fancy editable prespective images'
	}, 
	{
		'image': '//1452453094.rsc.cdn77.org/r-0000000/public/products/socialkitpro_4JSd3w6.png',
		'download_links': {
			'exe': '/download/socialkitpro/exe/',
			'zip': '/download/socialkitpro/zip/',
			'dmg': '/download/socialkitpro/dmg/'
		},
		'licensed': 'True',
		'visible': 'True',
		'video': '//1452453094.rsc.cdn77.org/r-0000000/public/products/videos/socialkitpro.mp4',
		'id': 57,
		'current_version': 10006,
		'targets': 'dmg,exe,zip',
		'last_update_date_formated': 'Jun 21, 2016',
		'author': 'Source',
		'support': 'Photoshop CC2015',
		'license_required': 'True',
		'platform': 'Photoshop',
		'buy_url': '/payment/socialkitkit-pro/',
		'internal_name': 'socialkitpro',
		'os_free': 'False',
		'badge': '',
		'order_priority': 70,
		'author_url': 'https://madebysource.com/',
		'description': 'Photoshop templates for your social media in a powerfull plugin. Preview, create and export pixel perfect pics & ads for all of your social media channels. 4 pixel perfect mobile and desktop advertising templates. 8 pixel perfect mobile and desktop templates for your profile and content testing.',
		'price': '39.99',
		'old_price': 'None',
		'old_price_split': ['None'],
		'price_split': ['39', '99'],
		'badge_color': '',
		'key_features': ['Photoshop templates for your social media', 'Including cover, profile photo & ads', 'Always up-to-date ', 'Easy import & export of all assets', '8 main social media templates included', 'Mobile templates', ''],
		'name': 'Social Kit Pro',
		'url': 'http://socialkit.madebysource.com/',
		'short_description': 'Social Kit Pro',
		'download_count': 3483,
		'current_version_formatted': '1.0.6',
		'popular': 'True',
		'bf_line': 'Create beautiful ads and social identity'
	}, 
	{
		'image': '//1452453094.rsc.cdn77.org/r-0000000/public/products/subtlepatterns.png',
		'download_links': {
			'exe': '/download/subtlepatterns/exe/',
			'zip': '/download/subtlepatterns/zip/',
			'dmg': '/download/subtlepatterns/dmg/'
		},
		'licensed': 'True',
		'visible': 'True',
		'video': '//1452453094.rsc.cdn77.org/r-0000000/public/products/videos/subtlepatterns.mp4',
		'id': 3,
		'current_version': 10503,
		'targets': 'dmg,exe,zip',
		'last_update_date_formated': 'Sep 15, 2016',
		'author': 'Source',
		'support': 'Photoshop CS5, CS6, CC, CC2014, CC2015',
		'license_required': 'True',
		'platform': 'Photoshop',
		'buy_url': '/payment/subtle-ps-general/',
		'internal_name': 'subtlepatterns',
		'os_free': 'False',
		'badge': '',
		'order_priority': 73,
		'author_url': 'https://madebysource.com/',
		'description': 'Immense library from Subtle Patterns, fed directly into your Photoshop panel – always in sync! ',
		'price': '17.99',
		'old_price': 'None',
		'old_price_split': ['None'],
		'price_split': ['17', '99'],
		'badge_color': '',
		'key_features': ['Apply instantly', 'Always synced', 'Build your collection', 'Export by one click'],
		'name': 'Subtle Patterns',
		'url': 'http://plugin.subtlepatterns.com/',
		'short_description': 'Immense library from Subtle Patterns, fed directly into your Photoshop panel – always in sync! ',
		'download_count': 84364,
		'current_version_formatted': '1.5.3',
		'popular': 'False',
		'bf_line': 'Immense textures library for your design always updated.'
	}, 
	{
		'image': '//1452453094.rsc.cdn77.org/r-0000000/public/products/sketch-states.png',
		'download_links': {
			'zip': '/download/sketch-states/zip/'
		},
		'licensed': 'True',
		'visible': 'True',
		'video': '//1452453094.rsc.cdn77.org/r-0000000/public/products/videos/sketch-states.mp4',
		'id': 63,
		'current_version': 909,
		'targets': 'dmg,zip',
		'last_update_date_formated': 'Sep 12, 2016',
		'author': 'Eden Vidal',
		'support': 'Sketch 3.5+',
		'license_required': 'False',
		'platform': 'Sketch',
		'buy_url': '/signup/sketch-states/',
		'internal_name': 'sketch-states',
		'os_free': 'False',
		'badge': '',
		'order_priority': 74,
		'author_url': 'http://states.design/',
		'description': 'Create different states and switch between them easily. Just like layer comps for Sketch.',
		'price': 'None',
		'old_price': 'None',
		'old_price_split': ['None'],
		'price_split': ['None'],
		'badge_color': '',
		'key_features': ['Define different positions', 'Toggle visibility of your layer', 'Create new states and update changes', 'Create pages with new artboards from your states'],
		'name': 'Sketch States',
		'url': 'http://states.design/',
		'short_description': 'Create different states and switch between them easily. Just like layer comps for Sketch.',
		'download_count': 3001,
		'current_version_formatted': '0.9.9',
		'popular': 'False',
		'bf_line': 'Create different states and switch between them easily'
	}, 
	{
		'image': '//1452453094.rsc.cdn77.org/r-0000000/public/products/color-kit.png',
		'download_links': {
			'exe': '/download/colorkit/exe/',
			'zip': '/download/colorkit/zip/',
			'dmg': '/download/colorkit/dmg/'
		},
		'licensed': 'True',
		'visible': 'True',
		'video': '//1452453094.rsc.cdn77.org/r-0000000/public/products/videos/color-kit.mp4',
		'id': 66,
		'current_version': 10000,
		'targets': 'dmg,exe,zip',
		'last_update_date_formated': 'Sep 13, 2016',
		'author': 'PluginMate',
		'support': 'Photoshop CC 2014+',
		'license_required': 'True',
		'platform': 'Photoshop',
		'buy_url': '/payment/color-kit/',
		'internal_name': 'colorkit',
		'os_free': 'False',
		'badge': '',
		'order_priority': 74,
		'author_url': 'https://pluginmate.com/',
		'description': 'Photoshop tool for color management. You can easily organize colors into projects and link them with a layer in a single click.',
		'price': '19.99',
		'old_price': 'None',
		'old_price_split': ['None'],
		'price_split': ['19', '99'],
		'badge_color': '',
		'key_features': ['Organize colors into projects', 'Link layers with colors', 'Auto-update colors between PSDs', 'Speed up your workflow'],
		'name': 'ColorKit',
		'url': 'https://colorkit.pluginmate.com/',
		'short_description': 'Photoshop tool for color management. You can easily organize colors into projects and link them with a layer in a single click.',
		'download_count': 484,
		'current_version_formatted': '1.0.0',
		'popular': 'False',
		'bf_line': 'Easily organize colors in projects, link them in layers'
	}, 
	{
		'image': '//1452453094.rsc.cdn77.org/r-0000000/public/products/fontea_sk1sZnc.png',
		'download_links': {
			'exe': '/download/fontea/exe/',
			'zip': '/download/fontea/zip/',
			'dmg': '/download/fontea/dmg/'
		},
		'licensed': 'True',
		'visible': 'True',
		'video': '//1452453094.rsc.cdn77.org/r-0000000/public/products/videos/fontea.mp4',
		'id': 60,
		'current_version': 10000,
		'targets': 'dmg,zip,exe',
		'last_update_date_formated': 'May 24, 2016',
		'author': 'Source',
		'support': 'Photoshop CC 2014, CC 2015',
		'license_required': 'False',
		'platform': 'Photoshop',
		'buy_url': '/signup/fontea/',
		'internal_name': 'fontea',
		'os_free': 'False',
		'badge': '',
		'order_priority': 75,
		'author_url': 'https://madebysource.com/',
		'description':  "Do you hate Photoshop native font selection? We do too. That's why we made Fontea. A Photoshop plugin that has all 700 Google Fonts included. Try it out for free!",
		'price': 'None',
		'old_price': 'None',
		'old_price_split': ['None'],
		'price_split': ['None'],
		'badge_color': '',
		'key_features': ['800 Google fonts in your Photoshop', 'Just one click to apply', 'Create your favorite fonts collection', 'Browse all categories as on web', 'Always up-to-date with Google Fonts library', ''],
		'name': 'Fontea',
		'url': 'https://fontea.madebysource.com/',
		'short_description': '700 Google fonts right inside your Photoshop',
		'download_count': 26169,
		'current_version_formatted': '1.0.0',
		'popular': 'True',
		'bf_line': ''
	}, 
	{
		'image': '//1452453094.rsc.cdn77.org/r-0000000/public/products/screensnap.png',
		'download_links': {
			'exe': '/download/screensnap/exe/',
			'zip': '/download/screensnap/zip/',
			'dmg': '/download/screensnap/dmg/'
		},
		'licensed': 'True',
		'visible': 'True',
		'video': '//1452453094.rsc.cdn77.org/r-0000000/public/products/videos/screensnap.mp4',
		'id': 70,
		'current_version': 10000,
		'targets': 'dmg,exe,zip',
		'last_update_date_formated': 'Sep 13, 2016',
		'author': 'PluginMate',
		'support': 'Photoshop CC 2014+',
		'license_required': 'True',
		'platform': 'Photoshop',
		'buy_url': '/payment/screen-snap/',
		'internal_name': 'screensnap',
		'os_free': 'False',
		'badge': '',
		'order_priority': 76,
		'author_url': 'https://pluginmate.com/',
		'description': 'Create normal or retina screenshots of your design from Photoshop faster than ever. Select a folder, choose your settings and press the button!',
		'price': '9.99',
		'old_price': 'None',
		'old_price_split': ['None'],
		'price_split': ['9', '99'],
		'badge_color': '',
		'key_features': ['Choose settings once', 'Create @2x retina screenshots', 'Save time'],
		'name': 'ScreenSnap',
		'url': 'https://screensnap.pluginmate.com/',
		'short_description': 'Create normal or retina screenshots of your design from Photoshop faster than ever. Select a folder, choose your settings and press the button!',
		'download_count': 14084,
		'current_version_formatted': '1.0.0',
		'popular': 'False',
		'bf_line': 'Create normal or retina screenshots of your design'
	}, 
	{
		'image': '//1452453094.rsc.cdn77.org/r-0000000/public/products/uber-spacer_6LkWNKr.png',
		'download_links': {
			'exe': '/download/uber-spacer/exe/',
			'zip': '/download/uber-spacer/zip/',
			'dmg': '/download/uber-spacer/dmg/'
		},
		'licensed': 'True',
		'visible': 'True',
		'video': '//1452453094.rsc.cdn77.org/r-0000000/public/products/videos/uber-spacer.mp4',
		'id': 76,
		'current_version': 10000,
		'targets': 'dmg,exe,zip',
		'last_update_date_formated': 'Sep 13, 2016',
		'author': 'UberPlugins',
		'support': 'Photoshop CC, CC 2014, CC 2015',
		'license_required': 'True',
		'platform': 'Photoshop',
		'buy_url': '/payment/uber-spacer/',
		'internal_name': 'uber-spacer',
		'os_free': 'False',
		'badge': '',
		'order_priority': 77,
		'author_url': 'http://uberplugins.cc/',
		'description': 'Distribute an equal amount of space between each object in Photoshop. Works with layer groups and any objects!',
		'price': '4.99',
		'old_price': 'None',
		'old_price_split': ['None'],
		'price_split': ['4', '99'],
		'badge_color': '',
		'key_features': ['Easiest centering in Photoshop', 'Equal amount of space', 'Works with layers, groups & smart objects'],
		'name': 'UberSpacer',
		'url': 'http://uberplugins.cc/',
		'short_description': 'Distribute an equal amount of space between each object in Photoshop. Works with layer groups and any objects!',
		'download_count': 16060,
		'current_version_formatted': '1.0.0',
		'popular': 'False',
		'bf_line': 'Distribute an equal amount of space between each object'
	}, 
	{
		'image': '//1452453094.rsc.cdn77.org/r-0000000/public/products/fontic.png',
		'download_links': {
			'exe': '/download/fontic/exe/',
			'zip': '/download/fontic/zip/',
			'dmg': '/download/fontic/dmg/'
		},
		'licensed': 'True',
		'visible': 'True',
		'video': '//1452453094.rsc.cdn77.org/r-0000000/public/products/videos/fontic.mp4',
		'id': 69,
		'current_version': 10000,
		'targets': 'dmg,exe,zip',
		'last_update_date_formated': 'Sep 13, 2016',
		'author': 'PluginMate',
		'support': 'Photoshop CC 2014+',
		'license_required': 'True',
		'platform': 'Photoshop',
		'buy_url': '/payment/fontic/',
		'internal_name': 'fontic',
		'os_free': 'False',
		'badge': '',
		'order_priority': 78,
		'author_url': 'https://pluginmate.com/',
		'description': 'Scan your PSD file and get a list of fonts used. Choose between Typekit and Google Fonts and easily include webfonts on your website!',
		'price': '14.99',
		'old_price': 'None',
		'old_price_split': ['None'],
		'price_split': ['14', '99'],
		'badge_color': '',
		'key_features': ['Typekit & Google Fonts support', 'Scan PSD for fonts	', 'Generate HTML code'],
		'name': 'Fontic',
		'url': 'https://fontic.pluginmate.com/',
		'short_description': 'Scan your PSD file and get a list of fonts used. Choose between Typekit and Google Fonts and easily include webfonts on your website!',
		'download_count': 21,
		'current_version_formatted': '1.0.0',
		'popular': 'False',
		'bf_line': 'Scan PSD, get a list of fonts used, Typekit & Google Fonts'
	}, 
	{
		'image': '//1452453094.rsc.cdn77.org/r-0000000/public/products/pixabay_pRnkZBB.png',
		'download_links': {
			'exe': '/download/pixabay/exe/',
			'zip': '/download/pixabay/zip/',
			'dmg': '/download/pixabay/dmg/'
		},
		'licensed': 'True',
		'visible': 'True',
		'video': '//1452453094.rsc.cdn77.org/r-0000000/public/products/videos/pixabay.mp4',
		'id': 61,
		'current_version': 10000,
		'targets': 'dmg,exe,zip',
		'last_update_date_formated': 'Jun 08, 2016',
		'author': 'Source',
		'support': 'Photoshop CC 2015 and higher',
		'license_required': 'True',
		'platform': 'Photoshop',
		'buy_url': '/payment/pixabay-photoshop-sdqwecP/',
		'internal_name': 'pixabay',
		'os_free': 'False',
		'badge': '',
		'order_priority': 80,
		'author_url': 'https://madebysource.com/',
		'description': 'Pixabay Photos in Your Photoshop and Sketch. Search for 600.000+ free stock photos and add them to your artboard at the click of a button.',
		'price': '4.99',
		'old_price': 'None',
		'old_price_split': ['None'],
		'price_split': ['4', '99'],
		'badge_color': '',
		'key_features': ['600.000+ free stock photos', 'Powerful Search Features', 'Just Click — It Will Fit', 'CC0 License on all images'],
		'name': 'Pixabay',
		'url': 'http://pixabay.madebysource.com/',
		'short_description': 'Pixabay Photos in Your Photoshop. Search for 600.000+ free stock photos and add them to your artboard at the click of a button.',
		'download_count': 17699,
		'current_version_formatted': '1.0.0',
		'popular': 'False',
		'bf_line': 'Over 600.000 CC0 stock photos inside Photoshop'
	}, 
	{
		'image': '//1452453094.rsc.cdn77.org/r-0000000/public/products/subtle-patterns-sketch_LYfxolt.png',
		'download_links': {
			'dmg': '/download/subtle-patterns-sketch/dmg/'
		},
		'licensed': 'True',
		'visible': 'True',
		'video': '//1452453094.rsc.cdn77.org/r-0000000/public/products/videos/subtle-patterns-sketch.mp4',
		'id': 58,
		'current_version': 10002,
		'targets': 'dmg',
		'last_update_date_formated': 'Oct 03, 2016',
		'author': 'Source',
		'support': 'Sketch 3.5+',
		'license_required': 'True',
		'platform': 'Sketch',
		'buy_url': '/payment/subtle-sketch-general/',
		'internal_name': 'subtle-patterns-sketch',
		'os_free': 'False',
		'badge': '',
		'order_priority': 103,
		'author_url': 'https://madebysource.com/',
		'description': 'Immense library from Subtle Patterns, fed directly into your Photoshop panel – always in sync! ',
		'price': '17.99',
		'old_price': 'None',
		'old_price_split': ['None'],
		'price_split': ['17', '99'],
		'badge_color': '',
		'key_features': ['Apply instantly', 'Always synced', 'Build your collection', 'Export by one click'],
		'name': 'Subtle Patterns',
		'url': 'http://plugin.subtlepatterns.com/',
		'short_description': 'Immense library from Subtle Patterns, fed directly into your Photoshop panel – always in sync! ',
		'download_count': 4235,
		'current_version_formatted': '1.0.2',
		'popular': 'True',
		'bf_line': 'Immense textures library for your design always updated.'
	}, 
	{
		'image': '//1452453094.rsc.cdn77.org/r-0000000/public/products/ioshat.png',
		'download_links': {
			'exe': '/download/ioshat/exe/',
			'zip': '/download/ioshat/zip/',
			'dmg': '/download/ioshat/dmg/'
		},
		'licensed': 'True',
		'visible': 'True',
		'video': '//1452453094.rsc.cdn77.org/r-0000000/public/products/videos/ioshat.mp4',
		'id': 11,
		'current_version': 10201,
		'targets': 'dmg,exe,zip',
		'last_update_date_formated': 'Jul 01, 2015',
		'author': 'Source',
		'support': 'Photoshop CS5, CS6, CC, CC2014, 2015.5',
		'license_required': 'True',
		'platform': 'Photoshop',
		'buy_url': '/payment/ios-hat/',
		'internal_name': 'ioshat',
		'os_free': 'False',
		'badge': '',
		'order_priority': 108,
		'author_url': 'None',
		'description': 'iOS Hat lets you build iOS apps from Photoshop designs faster! Instantly get colors, shapes, font styles, text, PNGs and dimensions.',
		'price': '39.99',
		'old_price': 'None',
		'old_price_split': ['None'],
		'price_split': ['39', '99'],
		'badge_color': '',
		'key_features': ['Turn Photoshop layers into Objective-C or Swift.', 'Export UIColor, Bézier Path or Font Style.', 'Export PNGs and implement right away.'],
		'name': 'iOS Hat',
		'url': 'http://ioshat.madebysource.com/',
		'short_description': 'iOS Hat lets you build iOS apps from Photoshop designs faster! Instantly get colors, shapes, font styles, text, PNGs and dimensions.',
		'download_count': 4345,
		'current_version_formatted': '1.2.1',
		'popular': 'False',
		'bf_line': 'Get colors, shapes, font styles in Swift/Objective C'
	}, 
	{
		'image': '//1452453094.rsc.cdn77.org/r-0000000/public/products/csshat.png',
		'download_links': {
			'exe': '/download/csshat/exe/',
			'zip': '/download/csshat/zip/',
			'dmg': '/download/csshat/dmg/'
		},
		'licensed': 'True',
		'visible': 'True',
		'video': '//1452453094.rsc.cdn77.org/r-0000000/public/products/videos/csshat.mp4',
		'id': 1,
		'current_version': 10200,
		'targets': 'dmg,exe,zip',
		'last_update_date_formated': 'Nov 18, 2014',
		'author': 'Source',
		'support':  "Photoshop CS4, CS5, CS6, CC, Doesn't support CC 2014",
		'license_required': 'True',
		'platform': 'Photoshop',
		'buy_url': '/payment/csshat/',
		'internal_name': 'csshat',
		'os_free': 'False',
		'badge': '',
		'order_priority': 'None',
		'author_url': 'None',
		'description': 'Photoshop plugin which instantly turns layer styles to CSS3! Speed-up your Photoshop workflow.',
		'price': '14.99',
		'old_price': 'None',
		'old_price_split': ['None'],
		'price_split': ['14', '99'],
		'badge_color': '',
		'key_features': ['Select any Photoshop Layer and get CSS instantly.', 'Colors, gradients, sizes, borders', 'Font styles and paragraph styles', 'Simple to use and easy '],
		'name': 'CSS Hat 1',
		'url': 'https://csshat.com/',
		'short_description': 'CSS Hat is a Photoshop plugin which instantly turns layer styles to CSS3! ',
		'download_count': 17732,
		'current_version_formatted': '1.2.0',
		'popular': 'False',
		'bf_line': 'Instantly turns layer styles to CSS3!'
	}, 
	{
		'image': '//1452453094.rsc.cdn77.org/r-0000000/public/products/pixabay-sketch_sPix1mj.png',
		'download_links': {
			'dmg': '/download/pixabay-sketch/dmg/'
		},
		'licensed': 'True',
		'visible': 'True',
		'video': '//1452453094.rsc.cdn77.org/r-0000000/public/products/videos/pixabay-sketch.mp4',
		'id': 62,
		'current_version': 10001,
		'targets': 'dmg',
		'last_update_date_formated': 'Aug 04, 2016',
		'author': 'Source',
		'support': 'Sketch 3.7+',
		'license_required': 'True',
		'platform': 'Sketch',
		'buy_url': '/payment/pixabay-sketch-sdqwecP/',
		'internal_name': 'pixabay-sketch',
		'os_free': 'False',
		'badge': '',
		'order_priority': 'None',
		'author_url': 'None',
		'description': 'Pixabay Photos in Your Sketch. Search for 600.000+ free stock photos and add them to your artboard at the click of a button.',
		'price': '4.99',
		'old_price': 'None',
		'old_price_split': ['None'],
		'price_split': ['4', '99'],
		'badge_color': '',
		'key_features': ['600.000+ free stock photos', 'Powerful Search Features', 'Just Click — It Will Fit', 'CC0 License on all images'],
		'name': 'Pixabay',
		'url': 'http://pixabay.madebysource.com/',
		'short_description': 'Pixabay Photos in Your Sketch. Search for 600.000+ free stock photos and add them to your artboard at the click of a button.',
		'download_count': 3106,
		'current_version_formatted': '1.0.1',
		'popular': 'False',
		'bf_line': 'Filter Over 600.000 Free licensed stock photos'
	}, 
	{
		'image': '//1452453094.rsc.cdn77.org/r-0000000/public/products/sort-me.png',
		'download_links': {
			'zip': '/download/sort-me/zip/'
		},
		'licensed': 'True',
		'visible': 'True',
		'video': '//1452453094.rsc.cdn77.org/r-0000000/public/products/videos/sort-me.mp4',
		'id': 64,
		'current_version': 10100,
		'targets': 'zip',
		'last_update_date_formated': 'Sep 12, 2016',
		'author': 'Roman Shamin',
		'support': 'Sketch 3.3+',
		'license_required': 'False',
		'platform': 'Sketch',
		'buy_url': '/signup/sort-me/',
		'internal_name': 'sort-me',
		'os_free': 'False',
		'badge': '',
		'order_priority': 'None',
		'author_url': 'None',
		'description': 'Organize your layers in Sketch file simply and efficiently.',
		'price': 'None',
		'old_price': 'None',
		'old_price_split': ['None'],
		'price_split': ['None'],
		'badge_color': '',
		'key_features': ['Organize layers', 'Organize artboards', 'Simple shorcut'],
		'name': 'Sort Me',
		'url': 'https://github.com/romashamin/sort-me-sketch',
		'short_description': 'Organize your layers in Sketch file simply and efficiently.',
		'download_count': 3019,
		'current_version_formatted': '1.1.0',
		'popular': 'False',
		'bf_line': 'Organize your layers in Sketch simply and efficiently'
	}, 
	{
		'image': '//1452453094.rsc.cdn77.org/r-0000000/public/products/state-machine.png',
		'download_links': {
			'zip': '/download/state-machine/zip/'
		},
		'licensed': 'True',
		'visible': 'True',
		'video': '//1452453094.rsc.cdn77.org/r-0000000/public/products/videos/state-machine.mp4',
		'id': 65,
		'current_version': 10100,
		'targets': 'zip',
		'last_update_date_formated': 'Sep 12, 2016',
		'author': 'Roman Shamin',
		'support': 'Sketch 3.9.1+',
		'license_required': 'False',
		'platform': 'Sketch',
		'buy_url': '/signup/state-machine/',
		'internal_name': 'state-machine',
		'os_free': 'False',
		'badge': '',
		'order_priority': 'None',
		'author_url': 'None',
		'description': 'State Machine is a Sketch plugin. Installing it will allow you to use ⌃⌘S to switch an active tab on a tab bar you’re designing, an active navigation section in a menu, or a page number in a pagination control.',
		'price': 'None',
		'old_price': 'None',
		'old_price_split': ['None'],
		'price_split': ['None'],
		'badge_color': '',
		'key_features': ['Switch an active tab', 'An active navigation section in a menu', 'Simply better navigation in your project'],
		'name': 'State Machine',
		'url': 'https://github.com/romashamin/statemachine-sketch',
		'short_description': 'State Machine is a Sketch plugin. Installing it will allow you to use ⌃⌘S to switch an active tab on a tab bar you’re designing, an active navigation section in a menu, or a page number in a pagination control.',
		'download_count': 2746,
		'current_version_formatted': '1.1.0',
		'popular': 'False',
		'bf_line': 'Create different states and switch between them easily'
	}, 
	{
		'image': '//1452453094.rsc.cdn77.org/r-0000000/public/products/uber-tuber_5tsa9su.png',
		'download_links': {
			'exe': '/download/uber-tuber/exe/',
			'zip': '/download/uber-tuber/zip/',
			'dmg': '/download/uber-tuber/dmg/'
		},
		'licensed': 'True',
		'visible': 'True',
		'video': '//1452453094.rsc.cdn77.org/r-0000000/public/products/videos/uber-tuber.mp4',
		'id': 71,
		'current_version': 100000,
		'targets': 'dmg,exe,zip',
		'last_update_date_formated': 'Sep 13, 2016',
		'author': 'Uber Plugins',
		'support': 'Photoshop CC 2014, CC 2015+',
		'license_required': 'True',
		'platform': 'Photoshop',
		'buy_url': '/payment/uber-tuber/',
		'internal_name': 'uber-tuber',
		'os_free': 'False',
		'badge': '',
		'order_priority': 'None',
		'author_url': 'None',
		'description': 'Insert Vimeo or YouTube videos into your Photoshop document with one click.',
		'price': '4.99',
		'old_price': 'None',
		'old_price_split': ['None'],
		'price_split': ['4', '99'],
		'badge_color': '',
		'key_features': ['Simple to use', 'One click away from inserting video preview', 'Editable design of the preview'],
		'name': 'UberTuber',
		'url': 'http://uberplugins.cc/',
		'short_description': 'Insert Vimeo or YouTube videos into your Photoshop document with one click.',
		'download_count': 6,
		'current_version_formatted': '10.0.0',
		'popular': 'False',
		'bf_line': 'Insert Vimeo or YouTube videos into your artboard'
	}, 
	{
		'image': '//1452453094.rsc.cdn77.org/r-0000000/public/products/uber-faces_GvqWuRY.png',
		'download_links': {
			'exe': '/download/uber-faces/exe/',
			'zip': '/download/uber-faces/zip/',
			'dmg': '/download/uber-faces/dmg/'
		},
		'licensed': 'True',
		'visible': 'True',
		'video': '//1452453094.rsc.cdn77.org/r-0000000/public/products/videos/uber-faces.mp4',
		'id': 72,
		'current_version': 10000,
		'targets': 'dmg,exe,zip',
		'last_update_date_formated': 'Oct 03, 2016',
		'author': 'UberPlugins',
		'support': 'Photoshop CC 2014, CC 2015+',
		'license_required': 'True',
		'platform': 'Photoshop',
		'buy_url': '/payment/uber-faces/',
		'internal_name': 'uber-faces',
		'os_free': 'False',
		'badge': '',
		'order_priority': 'None',
		'author_url': 'None',
		'description': 'Insert random face into selected area',
		'price': '4.99',
		'old_price': 'None',
		'old_price_split': ['None'],
		'price_split': ['4', '99'],
		'badge_color': '',
		'key_features': ['ability to insert picture in selected area', 'ability to insert in multiple avatars into selected layers by means of masking'],
		'name': 'UberFaces',
		'url': 'http://uberplugins.cc/',
		'short_description': 'Insert random face into selected area in your Photoshop.',
		'download_count': 13,
		'current_version_formatted': '1.0.0',
		'popular': 'False',
		'bf_line': 'Insert random face into selected area'
	}, 
	{
		'image': '//1452453094.rsc.cdn77.org/r-0000000/public/products/uber-line_uHL3Cbp.png',
		'download_links': {
			'exe': '/download/uber-line/exe/',
			'zip': '/download/uber-line/zip/',
			'dmg': '/download/uber-line/dmg/'
		},
		'licensed': 'True',
		'visible': 'True',
		'video': '//1452453094.rsc.cdn77.org/r-0000000/public/products/videos/uber-line.mp4',
		'id': 73,
		'current_version': 10000,
		'targets': 'dmg,exe,zip',
		'last_update_date_formated': 'Sep 23, 2016',
		'author': 'UberPlugins',
		'support': 'Photoshop CC, CC 2014, CC 2015',
		'license_required': 'True',
		'platform': 'Photoshop',
		'buy_url': '/payment/uber-line/',
		'internal_name': 'uber-line',
		'os_free': 'False',
		'badge': '',
		'order_priority': 'None',
		'author_url': 'None',
		'description': 'Create dotted, dashed and other custom link underlines for your texts in just a click. Easy to set your custom line width and transparency.',
		'price': '4.99',
		'old_price': 'None',
		'old_price_split': ['None'],
		'price_split': ['4', '99'],
		'badge_color': '',
		'key_features': ['Dotted, dashed and custom link underlines', 'Custom line width and transparency', 'Link line to layer or to folder'],
		'name': 'UberLine',
		'url': 'http://uberplugins.cc/',
		'short_description': 'Create dotted, dashed and other custom link underlines for your texts in just a click. Easy to set your custom line width and transparency.',
		'download_count': 12,
		'current_version_formatted': '1.0.0',
		'popular': 'False',
		'bf_line': 'Create dotted, dashed and custom underlines for texts'
	}, 
	{
		'image': '//1452453094.rsc.cdn77.org/r-0000000/public/products/uber-columns.png',
		'download_links': {
			'exe': '/download/uber-columns/exe/',
			'zip': '/download/uber-columns/zip/',
			'dmg': '/download/uber-columns/dmg/'
		},
		'licensed': 'True',
		'visible': 'True',
		'video': '//1452453094.rsc.cdn77.org/r-0000000/public/products/videos/uber-columns.mp4',
		'id': 74,
		'current_version': 1000,
		'targets': 'dmg,exe,zip',
		'last_update_date_formated': 'Oct 17, 2016',
		'author': 'UberPlugins',
		'support': 'Photoshop CC 2014',
		'license_required': 'True',
		'platform': 'Photoshop',
		'buy_url': '/payment/uber-columns/',
		'internal_name': 'uber-columns',
		'os_free': 'False',
		'badge': '',
		'order_priority': 'None',
		'author_url': 'None',
		'description': 'Effortlessly divide your paragraph text into columns. No need to manually update columns after each edit – UberColumns keeps your text layer intact, so editing text and layer styles does not affect the columns.',
		'price': '4.99',
		'old_price': 'None',
		'old_price_split': ['None'],
		'price_split': ['4', '99'],
		'badge_color': '',
		'key_features': ['One click from making text columns', 'Seamless distance between columns control', 'Easy to use'],
		'name': 'UberColumns',
		'url': 'http://uberplugins.cc/',
		'short_description': 'Effortlessly divide your paragraph text into columns. No need to manually update columns after each edit – UberColumns keeps your text layer intact, so editing text and layer styles does not affect the columns.',
		'download_count': 27,
		'current_version_formatted': '0.10.0',
		'popular': 'False',
		'bf_line': 'Effortlessly divide your paragraph text into columns'
	}, 
	{
		'image': '//1452453094.rsc.cdn77.org/r-0000000/public/products/uber-frame_AVjeTDL.png',
		'download_links': {
			'exe': '/download/uber-frame/exe/',
			'zip': '/download/uber-frame/zip/',
			'dmg': '/download/uber-frame/dmg/'
		},
		'licensed': 'True',
		'visible': 'True',
		'video': '//1452453094.rsc.cdn77.org/r-0000000/public/products/videos/uber-frame.mp4',
		'id': 75,
		'current_version': 10000,
		'targets': 'dmg,exe,zip',
		'last_update_date_formated': 'Sep 14, 2016',
		'author': 'UberPlugins',
		'support': 'Photoshop CC, CC 2014, CC 2015',
		'license_required': 'True',
		'platform': 'Photoshop',
		'buy_url': '/payment/uber-frame/',
		'internal_name': 'uber-frame',
		'os_free': 'False',
		'badge': '',
		'order_priority': 'None',
		'author_url': 'None',
		'description': 'Present your designs or mockups inside a browser window or a video player with just one click. Includes Safari (bold old and Yosemite version), Google Chrome, IE6, Yandex Browser, YouTube and Vimeo template. Make it your own with editable transparency and shadows.',
		'price': '4.99',
		'old_price': 'None',
		'old_price_split': ['None'],
		'price_split': ['4', '99'],
		'badge_color': '',
		'key_features': ['Showcase in browser', 'All major browsers', 'Vintage IE6', 'All templates editable'],
		'name': 'UberFrame',
		'url': 'http://uberplugins.cc/',
		'short_description': 'Present your designs or mockups inside a browser window or a video player with just one click. Includes Safari (bold old and Yosemite version), Google Chrome, IE6, Yandex Browser, YouTube and Vimeo template. Make it your own with editable transparency and shadows.',
		'download_count': 42,
		'current_version_formatted': '1.0.0',
		'popular': 'False',
		'bf_line': 'Present your designs inside a browser or a video player'
	}, 
	{
		'image': '//1452453094.rsc.cdn77.org/r-0000000/public/products/webalize.png',
		'download_links': {
			'zip': '/download/webalize/zip/'
		},
		'licensed': 'True',
		'visible': 'True',
		'video': '//1452453094.rsc.cdn77.org/r-0000000/public/products/videos/webalize.mp4',
		'id': 81,
		'current_version': 10000,
		'targets': 'zip',
		'last_update_date_formated': 'Oct 25, 2016',
		'author': 'David Veselý',
		'support': 'Sketch 39.1+',
		'license_required': 'False',
		'platform': 'Sketch',
		'buy_url': '/signup/webalize/',
		'internal_name': 'webalize',
		'os_free': 'False',
		'badge': 'New',
		'order_priority': 'None',
		'author_url': 'http://davidvesely.cz/',
		'description': 'Makes your layer or group names url-friendly and ready to export.',
		'price': 'None',
		'old_price': 'None',
		'old_price_split': ['None'],
		'price_split': ['None'],
		'badge_color': '#56A1F6',
		'key_features': ['Super easy to use', 'Webalize multiple layers or groups', 'Ideal for prepare layers (images, texts, shapes..) before export'],
		'name': 'Webalize',
		'url': 'https://github.com/Vesely/webalize',
		'short_description': 'Makes your layer or group names url-friendly and ready to export.',
		'download_count': 60,
		'current_version_formatted': '1.0.0',
		'popular': 'False',
		'bf_line': 'Makes your object names url-friendly and ready to export'
	}
]